apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog
  namespace: default
  labels:
    app: catalog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
    spec:
      containers:
        - name: catalog
          image: public.ecr.aws/aws-containers/retail-store-sample-catalog:0.4.0
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: project-rds.c8pa4q6a42qa.us-east-1.rds.amazonaws.com
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: catalogdb
            - name: DB_USER
              value: mydbuser
            - name: DB_PASSWORD
              value: ***REMOVED***
